### ISSUE TITLE
CL Front End Track Courses to be Completed

### ISSUE THREAD

**Issue by spdunn7** [spdunn7/treehouse#2]
## To-Do

*Courses left to complete the Treehouse CL Front End Track*

- [x] Introducing the VS Code Text Editor
- [x] CSS Layout Basics
- [x] Intro to the Terminal
- [x] Intro to Git
- [x] GitHub Basics
- [x] Debugging CSS w/ Chrome DevTools
- [x] Responsive Layouts
- [x] Practice Media Queries
- [x] CSS Flexbox Layout
- [x] HTML Forms
- [x] Practice Basic Variables, Input, & Output in JavaScript
- [x] JavaScript Numbers
- [x] JavaScript Functions
- [x] JavaScript Loops, Arrays, & Objects
- [x] CSS Selectors
- [x] Web Accessibility Compliance
- [x] Website Optimization
